package com.wakita181009.classic.model

enum class LineItemType {
    PLAN_CHARGE,
    USAGE_CHARGE,
    PRORATION_CREDIT,
    PRORATION_CHARGE,
    ADDON_CHARGE,
    ADDON_PRORATION_CREDIT,
    ADDON_PRORATION_CHARGE,
    SEAT_CHARGE,
    SEAT_PRORATION_CREDIT,
    SEAT_PRORATION_CHARGE,
    ACCOUNT_CREDIT,
}
